# период опроса
poll_every: "5m"

discord:
  webhook_url: ""
  mention: "<>"

  dmarket:
    public_key: ""
    secret_key: ""
    
# # телеграм-уведомления (опционально)
# telegram:
#   bot_token: "123456:ABCDEF..."   # создай @BotFather    
#   chat_id: "123456789"            # свой chat_id

# список наблюдаемых айтемов
items:
  # ===== non-StatTrak =====
  - title: "★ Butterfly Knife | Blue Steel (Factory New)"
    game_id: "a8db"
    my_target_usd: 480
    low_ask_alert_usd: 520
    top_n: 5

  - title: "★ Butterfly Knife | Blue Steel (Minimal Wear)"
    game_id: "a8db"
    my_target_usd: 430.00
    low_ask_alert_usd: 470.00
    top_n: 5

  - title: "★ Butterfly Knife | Blue Steel (Field-Tested)"
    game_id: "a8db"
    my_target_usd: 380.00
    low_ask_alert_usd: 420.00
    top_n: 5

  - title: "★ Butterfly Knife | Blue Steel (Well-Worn)"
    game_id: "a8db"
    my_target_usd: 350.00
    low_ask_alert_usd: 395.00
    top_n: 5

  - title: "★ Butterfly Knife | Blue Steel (Battle-Scarred)"
    game_id: "a8db"
    my_target_usd: 320.00
    low_ask_alert_usd: 360.00
    top_n: 5

  # ===== StatTrak™ =====
  - title: "StatTrak™ ★ Butterfly Knife | Blue Steel (Factory New)"
    game_id: "a8db"
    my_target_usd: 620.00
    low_ask_alert_usd: 680.00
    top_n: 5

  - title: "StatTrak™ ★ Butterfly Knife | Blue Steel (Minimal Wear)"
    game_id: "a8db"
    my_target_usd: 560.00
    low_ask_alert_usd: 620.00
    top_n: 5

  - title: "StatTrak™ ★ Butterfly Knife | Blue Steel (Field-Tested)"
    game_id: "a8db"
    my_target_usd: 500.00
    low_ask_alert_usd: 560.00
    top_n: 5

  - title: "StatTrak™ ★ Butterfly Knife | Blue Steel (Well-Worn)"
    game_id: "a8db"
    my_target_usd: 460.00
    low_ask_alert_usd: 520.00
    top_n: 5

  - title: "StatTrak™ ★ Butterfly Knife | Blue Steel (Battle-Scarred)"
    game_id: "a8db"
    my_target_usd: 420.00
    low_ask_alert_usd: 480.00
    top_n: 5